export { default as MyNavMenu } from './myNavMenu/MyNavMenu.vue'
export { default as MyHeader } from './myHeader/MyHeader.vue'
export { default as MyUpload } from './MyUpload.vue'
export { default as MyStep } from './myStep/MyStep.vue'
export { default as MySteps } from './myStep/MySteps.vue'
export { default as MyEditor } from './MyEditor.vue'
export { default as MySticky } from './MySticky.vue'
